modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="logo.png"

[[mods]]
modId="ramadandelight"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.ramadandelight]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.ramadandelight]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.ramadandelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.8,)"
    ordering="NONE"
    side="BOTH"