modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="logo.png"

[[mods]]
modId="ramadandelight"
version="${mod_version}"
displayName="Ramadan Delight"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.ramadandelight]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.ramadandelight]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ramadandelight]]
modId="farmersdelight"
type="required"
mandatory=true
versionRange="[1.2.8,)"
ordering="AFTER"
side="BOTH"